---
title: "Real Estate"
author: "Beatriz"

```date: "13/10/2020"
output: html_document
---

```{r, setup, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  tidy=FALSE,     # display code as typed
  size="small")   # slightly smaller font for code
options(digits = 3)

# default figure size
knitr::opts_chunk$set(
  fig.width=6.75, 
  fig.height=6.75,
  fig.align = "center"
)
```



```{r load-libraries, echo=FALSE}
library(tidyverse)  # Load ggplot2, dplyr, and all the other tidyverse packages
library(gapminder)  # gapminder dataset
library(here)
```


## Load the data


```{r}
glimpse(World_data)

```

```{r}
 World_data_new <- World_data %>%  
  rename("Population" = `Population, total [SP.POP.TOTL]`, "Year" = `Time`, "Country" = `Country Name`) %>%
  transform.data.frame(`Population` = as.numeric(as.character(`Population`)), `Year` = as.numeric(as.character(`Year`)))

World_data_new

```

## Create plot


```{r}
portugal_data <- World_data_new %>% 
            filter(`Country` == "Portugal")
portugal_data

```

```{r, population_grwoth_Portugal}
plot1 <- portugal_data %>% 
  ggplot(mapping = aes(x = `Year`, y = `Population`)) +
  geom_point() +
  theme_light()

plot1
```